version: '3'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=depublic
      - POSTGRES_PASSWORD=depublic
      - POSTGRES_DB=depublic
    ports:
      - "5432:5432"
    volumes: 
      - db_data:/var/lib/postgresql/data 
      - ./initdb:/docker-entrypoint-initdb.d 

volumes: 
  db_data:
